######################################################################
# Automatically generated by qmake (3.0) Mon Feb 17 22:48:14 2014
######################################################################

TEMPLATE = app
TARGET = ss2
INCLUDEPATH += .

# Input
HEADERS += myclass.h otherclass.h
SOURCES += main.cpp myclass.cpp otherclass.cpp
