######################################################################
# Automatically generated by qmake (3.0) Mon Feb 17 22:48:02 2014
######################################################################

TEMPLATE = app
TARGET = ss1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
